### ISSUE TITLE
Incompatibility of file formats

### ISSUE THREAD

**Issue by osnaiderp** [alexlib/pivpy#14]
I want to know if I can use PIVPy to process files that just have four columns (x, y, u, v), these files are not outputs of OpenPIV. I attach a sample file.

[B00001.txt](https://github.com/alexlib/pivpy/files/3470191/B00001.txt)

**Comment by alexlib** [comment]
@osnaiderp please see 

https://github.com/alexlib/pivpy/blob/4columns/examples/notebooks/test_4columns.ipynb
